- name: Install `yum-config-manager`
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  become: yes
- name: Add repository for Docker
  shell: 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
  become: yes
- name: Install docker ce
  yum:
    name: 'docker-ce'
    state: latest
  become: yes
- name: Install docker-compose
  shell: "curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose; chmod +x /usr/local/bin/docker-compose;"
  become: yes
- name: Enable docker service "on"
  command: "systemctl enable docker"
  become: yes
- name: Add docker group permission on vagrant
  shell: "gpasswd -a vagrant docker"
  become: yes
- name: Run docker service
  command: "systemctl start docker"
  become: yes
- name: Run docker containers
  shell: "docker-compose -f /vagrant/docker/docker-compose.yml up -d"
